---
title: "Cluster Profiler"
output: html_document
---

# Set environment
```{r}
library(clusterProfiler)
library(biomaRt)
library(org.Hs.eg.db)
library(ggplot2)
library(enrichplot)
library(magrittr)
```

# biomaRt
```{r}
#Creating the ensemble object
ensembl<-useMart("ensembl")
#This shows all of the possible organisms to work with
listDatasets(ensembl)
#Here I'm defining which organism I am working with, in this case human
ensembl <- useDataset("hsapiens_gene_ensembl",mart=ensembl)
```

# NEK1-containing modules 
```{r}
# Get the gene list of the NEK1-containing modules
Genelist.c1.blue=names(MC.c1.scaled[moduleColors.1=="blue"])
Genelist.c2.turquoise=names(MC.c2.scaled[moduleColors.2=="turquoise"])
Genelist.c3.red=names(MC.c3.scaled[moduleColors.3=="red"])
Genelist.c4.magenta=names(MC.c4.scaled[moduleColors.4=="magenta"])
Genelist.c5.cyan=names(MC.c5.scaled[moduleColors.5=="cyan"])
Genelist.c6.turquoise=names(MC.c6.scaled[moduleColors.6=="turquoise"])
Genelist.c7.yellow=names(MC.c7.scaled[moduleColors.7=="yellow"])
Genelist.c8.black=names(MC.c8.scaled[moduleColors.8=="black"])
Genelist.c9.turquoise=names(MC.c9.scaled[moduleColors.9=="turquoise"])
Genelist.c10.brown=names(MC.c10.scaled[moduleColors.10=="brown"])
Genelist.c11.turquoise=names(MC.c11.scaled[moduleColors.11=="turquoise"])
Genelist.c12.turquoise=names(MC.c12.scaled[moduleColors.12=="turquoise"])
Genelist.c13.brown=names(MC.c13.scaled[moduleColors.13=="brown"])
Genelist.c14.black=names(MC.c14.scaled[moduleColors.14=="black"])
Genelist.c15.pink=names(MC.c15.scaled[moduleColors.15=="pink"])
Genelist.c16.red=names(MC.c16.scaled[moduleColors.16=="red"])
Genelist.c18.turquoise=names(MC.c12.scaled[moduleColors.18=="turquoise"])

# Get the entrez ids for the genes
clusters=c(1:16, 18)
NEK1clusters=c("blue", "turquoise", "red", "magenta","cyan","turquoise", "yellow","black","turquoise","brown","turquoise","turquoise","brown","black", "pink", "red", "", "turquoise")

for (cluster in clusters) {
  object=mget(paste0("Genelist.c", cluster,".", NEK1clusters[cluster]))
  name=paste0("Genelist.c", cluster,".", NEK1clusters[cluster],".id")
  assign(name,getBM(attributes = c('external_gene_name','entrezgene_id',"gene_biotype"), filters='external_gene_name', values = object[1], mart = ensembl) )
}
  
# Functions
enrichGO_all<-function(x){
  clusterProfiler::enrichGO(gene=x$entrezgene_id, OrgDb = org.Hs.eg.db, ont="ALL",pAdjustMethod = "BH", pvalueCutoff  = 0.01, qvalueCutoff  = 0.05,readable = TRUE )
}

enrichGO_BP_Simple<-function(x){
  clusterProfiler::enrichGO(gene=x$entrezgene_id, OrgDb = org.Hs.eg.db, ont="BP",pAdjustMethod = "BH", pvalueCutoff  = 0.01, qvalueCutoff  = 0.05,readable = TRUE ) %>% clusterProfiler::simplify(cutoff=0.7, by="p.adjust", select_fun=min)
}

enrichGO_MF_Simple<-function(x){
  clusterProfiler::enrichGO(gene=x$entrezgene_id, OrgDb = org.Hs.eg.db, ont="MF",pAdjustMethod = "BH", pvalueCutoff  = 0.01, qvalueCutoff  = 0.05,readable = TRUE ) %>% clusterProfiler::simplify(cutoff=0.7, by="p.adjust", select_fun=min)
}

enrichGO_CC_Simple<-function(x){
  clusterProfiler::enrichGO(gene=x$entrezgene_id, OrgDb = org.Hs.eg.db, ont="CC",pAdjustMethod = "BH", pvalueCutoff  = 0.01, qvalueCutoff  = 0.05,readable = TRUE ) %>% clusterProfiler::simplify(cutoff=0.7, by="p.adjust", select_fun=min)
}


# Perform the GO enrichment analyses on the NEK1 modules
Genelists<-c(Genelist.c1.blue.id, Genelist.c2.turquoise.id, Genelist.c3.red.id, Genelist.c4.magenta.id, Genelist.c5.cyan.id, Genelist.c6.turquoise.id, Genelist.c7.yellow.id, Genelist.c8.black.id, Genelist.c9.turquoise.id, Genelist.c10.brown.id, Genelist.c11.turquoise.id, Genelist.c12.turquoise.id, Genelist.c13.brown.id, Genelist.c14.black.id, Genelist.c15.pink.id, Genelist.c16.red.id, Genelist.c18.turquoise.id)
names<-c("GO.c1.blue.all","GO.c2.turquoise.all", "GO.c3.red.all", "GO.c4.magenta.all", "GO.c5.cyan.all", "GO.c6.turquoise.all", "GO.c7.yellow.all", "GO.c8.black.all", "GO.c9.turquoise.all", "GO.c10.brown.all", "GO.c11.turquoise.all", "GO.c12.turquoise.all", "GO.c13.brown.all", "GO.c14.black.all", "GO.c15.pink.all", "GO.c16.red.all", "GO.c18.turquoise.all")
n=1

## All GO terms
for (i in c(2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50)){
  assign(names[n], enrichGO_all(Genelists[i]))
  n=n+1
}

## Biologial process, simplified
names<-c("GO.c1.blue.BPSimple","GO.c2.turquoise.BPSimple", "GO.c3.red.BPSimple", "GO.c4.magenta.BPSimple", "GO.c5.cyan.BPSimple", "GO.c6.turquoise.BPSimple", "GO.c7.yellow.BPSimple", "GO.c8.black.BPSimple", "GO.c9.turquoise.BPSimple", "GO.c10.brown.BPSimple", "GO.c11.turquoise.BPSimple", "GO.c12.turquoise.BPSimple", "GO.c13.brown.BPSimple", "GO.c14.black.BPSimple", "GO.c15.pink.BPSimple", "GO.c16.red.BPSimple", "GO.c18.turquoise.BPSimple")
n=1
for (i in c(2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50)){
  assign(names[n], enrichGO_BP_Simple(Genelists[i]))
  n=n+1
}

## Molecular function
names<-c("GO.c1.blue.MFSimple","GO.c2.turquoise.MFSimple", "GO.c3.red.MFSimple", "GO.c4.magenta.MFSimple", "GO.c5.cyan.MFSimple", "GO.c6.turquoise.MFSimple", "GO.c7.yellow.MFSimple", "GO.c8.black.MFSimple", "GO.c9.turquoise.MFSimple", "GO.c10.brown.MFSimple", "GO.c11.turquoise.MFSimple", "GO.c12.turquoise.MFSimple", "GO.c13.brown.MFSimple", "GO.c14.black.MFSimple", "GO.c15.pink.MFSimple", "GO.c16.red.MFSimple", "GO.c18.turquoise.MFSimple")
n=1
for (i in c(2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50)){
  assign(names[n], enrichGO_MF_Simple(Genelists[i]))
  n=n+1
}

## Cellular Component
names<-c("GO.c1.blue.CCSimple","GO.c2.turquoise.CCSimple", "GO.c3.red.CCSimple", "GO.c4.magenta.CCSimple", "GO.c5.cyan.CCSimple", "GO.c6.turquoise.CCSimple", "GO.c7.yellow.CCSimple", "GO.c8.black.CCSimple", "GO.c9.turquoise.CCSimple", "GO.c10.brown.CCSimple", "GO.c11.turquoise.CCSimple", "GO.c12.turquoise.CCSimple", "GO.c13.brown.CCSimple", "GO.c14.black.CCSimple", "GO.c15.pink.CCSimple", "GO.c16.red.CCSimple", "GO.c18.turquoise.CCSimple")
n=1
for (i in c(2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50)){
  assign(names[n], enrichGO_CC_Simple(Genelists[i]))
  n=n+1
}
```


# KEGG pathway
```{r}
# Function
KEGG<-function(x){
  clusterProfiler::enrichKEGG(gene=x$entrezgene_id, organism = 'hsa', pvalueCutoff = 0.05)
}

## NEK1
names<-c("KEGG.c1.blue","KEGG.c2.turquoise", "KEGG.c3.red", "KEGG.c4.magenta", "KEGG.c5.cyan", "KEGG.c6.turquoise", "KEGG.c7.yellow", "KEGG.c8.black", "KEGG.c9.turquoise", "KEGG.c10.brown", "KEGG.c11.turquoise", "KEGG.c12.turquoise", "KEGG.c13.brown", "KEGG.c14.black", "KEGG.c15.pink", "KEGG.c16.red", "KEGG.c18.turquoise")
n=1
for (i in c(2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50)){
  assign(names[n], KEGG(Genelists[i]))
  n=n+1
}
```

# Visualize
```{r}
## Visualize BP simple
SimpleBPs<-c(GO.c1.blue.BPSimple,GO.c2.turquoise.BPSimple, GO.c3.red.BPSimple, GO.c4.magenta.BPSimple, GO.c5.cyan.BPSimple, GO.c6.turquoise.BPSimple, GO.c7.yellow.BPSimple, GO.c8.black.BPSimple, GO.c9.turquoise.BPSimple, GO.c10.brown.BPSimple, GO.c11.turquoise.BPSimple, GO.c12.turquoise.BPSimple, GO.c13.brown.BPSimple, GO.c14.black.BPSimple, GO.c15.pink.BPSimple, GO.c16.red.BPSimple, GO.c18.turquoise.BPSimple)
n=1
for (i in c(1:17)) {
  x<-dotplot(SimpleBPs[[i]], showCategory=5) + ggtitle(paste("dotplot for Simple BP cluster", n))
  print(plot_grid(x))
  n=n+1
}

## Visualize MF simple
SimpleMFs<-c(GO.c1.blue.MFSimple,GO.c2.turquoise.MFSimple, GO.c3.red.MFSimple, GO.c4.magenta.MFSimple, GO.c5.cyan.MFSimple, GO.c6.turquoise.MFSimple, GO.c7.yellow.MFSimple, GO.c8.black.MFSimple, GO.c9.turquoise.MFSimple, GO.c10.brown.MFSimple, GO.c11.turquoise.MFSimple, GO.c12.turquoise.MFSimple, GO.c13.brown.MFSimple, GO.c14.black.MFSimple, GO.c15.pink.MFSimple, GO.c16.red.MFSimple, GO.c18.turquoise.MFSimple)
n=1
for (i in c(1:17)) {
  x<-dotplot(SimpleMFs[[i]], showCategory=5) + ggtitle(paste("dotplot for Simple MF cluster", n))
  print(plot_grid(x))
  n=n+1
}

## Visualize CC simple
SimpleBPs<-c(GO.c1.blue.CCSimple,GO.c2.turquoise.CCSimple, GO.c3.red.CCSimple, GO.c4.magenta.CCSimple, GO.c5.cyan.CCSimple, GO.c6.turquoise.CCSimple, GO.c7.yellow.CCSimple, GO.c8.black.CCSimple, GO.c9.turquoise.CCSimple, GO.c10.brown.CCSimple, GO.c11.turquoise.CCSimple, GO.c12.turquoise.CCSimple, GO.c13.brown.CCSimple, GO.c14.black.CCSimple, GO.c15.pink.CCSimple, GO.c16.red.CCSimple, GO.c18.turquoise.CCSimple)
n=1
for (i in c(1:17)) {
  x<-dotplot(SimpleCCs[[i]], showCategory=5) + ggtitle(paste("dotplot for Simple CC cluster", n))
  print(plot_grid(x))
  n=n+1
}


## Visualize ALL
GOalls<-c(GO.c1.blue.all, GO.c2.turquoise.all, GO.c3.red.all, GO.c4.magenta.all, GO.c5.cyan.all, GO.c6.turquoise.all, GO.c7.yellow.all, GO.c8.black.all, GO.c9.turquoise.all, GO.c10.brown.all, GO.c11.turquoise.all, GO.c12.turquoise.all, GO.c13.brown.all, GO.c14.black.all, GO.c15.pink.all, GO.c16.red.all, GO.c18.turquoise.all)

n=1
for (i in c(1:17)) {
  x<-dotplot(GOalls[[i]], showCategory=5) + ggtitle(paste("dotplot for ALL GO cluster", n))
  print(plot_grid(x))
  n=n+1
}

## Visualize KEGG
### NEK1
KEGGs<-names<-c(KEGG.c1.blue,KEGG.c2.turquoise, KEGG.c3.red,KEGG.c4.magenta,KEGG.c5.cyan,KEGG.c6.turquoise, KEGG.c7.yellow, KEGG.c8.black,KEGG.c9.turquoise,KEGG.c10.brown, KEGG.c11.turquoise, KEGG.c12.turquoise, KEGG.c13.brown, KEGG.c14.black, KEGG.c15.pink,KEGG.c16.red,KEGG.c18.turquoise)
n=1
for (i in c(1:17)) {
  x<-dotplot(KEGGs[[i]], showCategory=5) + ggtitle(paste("dotplot for KEGG cluster", n))
  print(plot_grid(x))
  n=n+1
}

```
